// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BlockchainDtos.proto

// Protobuf Java Version: 3.25.1
package ru.itislabs.blockchains.dto;

/**
 * Protobuf type {@code ru.itislabs.blockchains.dto.BlockDto}
 */
public final class BlockDto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.itislabs.blockchains.dto.BlockDto)
    BlockDtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BlockDto.newBuilder() to construct.
  private BlockDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BlockDto() {
    data_ = com.google.protobuf.ByteString.EMPTY;
    dataSignature_ = com.google.protobuf.ByteString.EMPTY;
    hashSignature_ = com.google.protobuf.ByteString.EMPTY;
    previousBlockHash_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BlockDto();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itislabs.blockchains.dto.BlockchainDtos.internal_static_ru_itislabs_blockchains_dto_BlockDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itislabs.blockchains.dto.BlockchainDtos.internal_static_ru_itislabs_blockchains_dto_BlockDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itislabs.blockchains.dto.BlockDto.class, ru.itislabs.blockchains.dto.BlockDto.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  public static final int DATASIGNATURE_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString dataSignature_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes dataSignature = 3;</code>
   * @return The dataSignature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDataSignature() {
    return dataSignature_;
  }

  public static final int HASHSIGNATURE_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString hashSignature_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes hashSignature = 4;</code>
   * @return The hashSignature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getHashSignature() {
    return hashSignature_;
  }

  public static final int PREVIOUSBLOCKHASH_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString previousBlockHash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>optional bytes previousBlockHash = 5;</code>
   * @return Whether the previousBlockHash field is set.
   */
  @java.lang.Override
  public boolean hasPreviousBlockHash() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bytes previousBlockHash = 5;</code>
   * @return The previousBlockHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPreviousBlockHash() {
    return previousBlockHash_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!data_.isEmpty()) {
      output.writeBytes(2, data_);
    }
    if (!dataSignature_.isEmpty()) {
      output.writeBytes(3, dataSignature_);
    }
    if (!hashSignature_.isEmpty()) {
      output.writeBytes(4, hashSignature_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBytes(5, previousBlockHash_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, data_);
    }
    if (!dataSignature_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, dataSignature_);
    }
    if (!hashSignature_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, hashSignature_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, previousBlockHash_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itislabs.blockchains.dto.BlockDto)) {
      return super.equals(obj);
    }
    ru.itislabs.blockchains.dto.BlockDto other = (ru.itislabs.blockchains.dto.BlockDto) obj;

    if (getId()
        != other.getId()) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!getDataSignature()
        .equals(other.getDataSignature())) return false;
    if (!getHashSignature()
        .equals(other.getHashSignature())) return false;
    if (hasPreviousBlockHash() != other.hasPreviousBlockHash()) return false;
    if (hasPreviousBlockHash()) {
      if (!getPreviousBlockHash()
          .equals(other.getPreviousBlockHash())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + DATASIGNATURE_FIELD_NUMBER;
    hash = (53 * hash) + getDataSignature().hashCode();
    hash = (37 * hash) + HASHSIGNATURE_FIELD_NUMBER;
    hash = (53 * hash) + getHashSignature().hashCode();
    if (hasPreviousBlockHash()) {
      hash = (37 * hash) + PREVIOUSBLOCKHASH_FIELD_NUMBER;
      hash = (53 * hash) + getPreviousBlockHash().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itislabs.blockchains.dto.BlockDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itislabs.blockchains.dto.BlockDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itislabs.blockchains.dto.BlockDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itislabs.blockchains.dto.BlockDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itislabs.blockchains.dto.BlockDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itislabs.blockchains.dto.BlockDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itislabs.blockchains.dto.BlockDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itislabs.blockchains.dto.BlockDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ru.itislabs.blockchains.dto.BlockDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ru.itislabs.blockchains.dto.BlockDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itislabs.blockchains.dto.BlockDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itislabs.blockchains.dto.BlockDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itislabs.blockchains.dto.BlockDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.itislabs.blockchains.dto.BlockDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.itislabs.blockchains.dto.BlockDto)
      ru.itislabs.blockchains.dto.BlockDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itislabs.blockchains.dto.BlockchainDtos.internal_static_ru_itislabs_blockchains_dto_BlockDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itislabs.blockchains.dto.BlockchainDtos.internal_static_ru_itislabs_blockchains_dto_BlockDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itislabs.blockchains.dto.BlockDto.class, ru.itislabs.blockchains.dto.BlockDto.Builder.class);
    }

    // Construct using ru.itislabs.blockchains.dto.BlockDto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
      dataSignature_ = com.google.protobuf.ByteString.EMPTY;
      hashSignature_ = com.google.protobuf.ByteString.EMPTY;
      previousBlockHash_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itislabs.blockchains.dto.BlockchainDtos.internal_static_ru_itislabs_blockchains_dto_BlockDto_descriptor;
    }

    @java.lang.Override
    public ru.itislabs.blockchains.dto.BlockDto getDefaultInstanceForType() {
      return ru.itislabs.blockchains.dto.BlockDto.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itislabs.blockchains.dto.BlockDto build() {
      ru.itislabs.blockchains.dto.BlockDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itislabs.blockchains.dto.BlockDto buildPartial() {
      ru.itislabs.blockchains.dto.BlockDto result = new ru.itislabs.blockchains.dto.BlockDto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ru.itislabs.blockchains.dto.BlockDto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.data_ = data_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.dataSignature_ = dataSignature_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.hashSignature_ = hashSignature_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.previousBlockHash_ = previousBlockHash_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itislabs.blockchains.dto.BlockDto) {
        return mergeFrom((ru.itislabs.blockchains.dto.BlockDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itislabs.blockchains.dto.BlockDto other) {
      if (other == ru.itislabs.blockchains.dto.BlockDto.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      if (other.getDataSignature() != com.google.protobuf.ByteString.EMPTY) {
        setDataSignature(other.getDataSignature());
      }
      if (other.getHashSignature() != com.google.protobuf.ByteString.EMPTY) {
        setHashSignature(other.getHashSignature());
      }
      if (other.hasPreviousBlockHash()) {
        setPreviousBlockHash(other.getPreviousBlockHash());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              data_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              dataSignature_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              hashSignature_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              previousBlockHash_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 2;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      data_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bytes data = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000002);
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString dataSignature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes dataSignature = 3;</code>
     * @return The dataSignature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDataSignature() {
      return dataSignature_;
    }
    /**
     * <code>bytes dataSignature = 3;</code>
     * @param value The dataSignature to set.
     * @return This builder for chaining.
     */
    public Builder setDataSignature(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      dataSignature_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bytes dataSignature = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataSignature() {
      bitField0_ = (bitField0_ & ~0x00000004);
      dataSignature_ = getDefaultInstance().getDataSignature();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString hashSignature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes hashSignature = 4;</code>
     * @return The hashSignature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHashSignature() {
      return hashSignature_;
    }
    /**
     * <code>bytes hashSignature = 4;</code>
     * @param value The hashSignature to set.
     * @return This builder for chaining.
     */
    public Builder setHashSignature(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      hashSignature_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bytes hashSignature = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHashSignature() {
      bitField0_ = (bitField0_ & ~0x00000008);
      hashSignature_ = getDefaultInstance().getHashSignature();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString previousBlockHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes previousBlockHash = 5;</code>
     * @return Whether the previousBlockHash field is set.
     */
    @java.lang.Override
    public boolean hasPreviousBlockHash() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bytes previousBlockHash = 5;</code>
     * @return The previousBlockHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPreviousBlockHash() {
      return previousBlockHash_;
    }
    /**
     * <code>optional bytes previousBlockHash = 5;</code>
     * @param value The previousBlockHash to set.
     * @return This builder for chaining.
     */
    public Builder setPreviousBlockHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      previousBlockHash_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes previousBlockHash = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreviousBlockHash() {
      bitField0_ = (bitField0_ & ~0x00000010);
      previousBlockHash_ = getDefaultInstance().getPreviousBlockHash();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.itislabs.blockchains.dto.BlockDto)
  }

  // @@protoc_insertion_point(class_scope:ru.itislabs.blockchains.dto.BlockDto)
  private static final ru.itislabs.blockchains.dto.BlockDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itislabs.blockchains.dto.BlockDto();
  }

  public static ru.itislabs.blockchains.dto.BlockDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlockDto>
      PARSER = new com.google.protobuf.AbstractParser<BlockDto>() {
    @java.lang.Override
    public BlockDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BlockDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlockDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itislabs.blockchains.dto.BlockDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

