// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BlockchainDtos.proto

// Protobuf Java Version: 3.25.1
package ru.itislabs.blockchains.dto;

public interface BlockchainDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itislabs.blockchains.dto.BlockchainDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ru.itislabs.blockchains.dto.BlockDto chain = 1;</code>
   */
  java.util.List<ru.itislabs.blockchains.dto.BlockDto> 
      getChainList();
  /**
   * <code>repeated .ru.itislabs.blockchains.dto.BlockDto chain = 1;</code>
   */
  ru.itislabs.blockchains.dto.BlockDto getChain(int index);
  /**
   * <code>repeated .ru.itislabs.blockchains.dto.BlockDto chain = 1;</code>
   */
  int getChainCount();
  /**
   * <code>repeated .ru.itislabs.blockchains.dto.BlockDto chain = 1;</code>
   */
  java.util.List<? extends ru.itislabs.blockchains.dto.BlockDtoOrBuilder> 
      getChainOrBuilderList();
  /**
   * <code>repeated .ru.itislabs.blockchains.dto.BlockDto chain = 1;</code>
   */
  ru.itislabs.blockchains.dto.BlockDtoOrBuilder getChainOrBuilder(
      int index);
}
