// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ru/itislabs/blockchains/dto/BlockchainDtos.proto

// Protobuf Java Version: 3.25.1
package ru.itislabs.blockchains.dto;

public interface BlockDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itislabs.blockchains.dto.BlockDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>bytes dataSignature = 3;</code>
   * @return The dataSignature.
   */
  com.google.protobuf.ByteString getDataSignature();

  /**
   * <code>bytes hashSignature = 4;</code>
   * @return The hashSignature.
   */
  com.google.protobuf.ByteString getHashSignature();

  /**
   * <code>bytes timestamp = 5;</code>
   * @return The timestamp.
   */
  com.google.protobuf.ByteString getTimestamp();

  /**
   * <code>optional bytes previousBlockHash = 6;</code>
   * @return Whether the previousBlockHash field is set.
   */
  boolean hasPreviousBlockHash();
  /**
   * <code>optional bytes previousBlockHash = 6;</code>
   * @return The previousBlockHash.
   */
  com.google.protobuf.ByteString getPreviousBlockHash();
}
