// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ru/itislabs/blockchains/dto/BlockchainDtos.proto

// Protobuf Java Version: 3.25.1
package ru.itislabs.blockchains.dto;

public final class BlockchainDtos {
  private BlockchainDtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itislabs_blockchains_dto_BlockDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itislabs_blockchains_dto_BlockDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itislabs_blockchains_dto_BlockchainDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itislabs_blockchains_dto_BlockchainDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0ru/itislabs/blockchains/dto/Blockchain" +
      "Dtos.proto\022\033ru.itislabs.blockchains.dto\"" +
      "\233\001\n\010BlockDto\022\n\n\002id\030\001 \001(\005\022\014\n\004data\030\002 \001(\014\022\025" +
      "\n\rdataSignature\030\003 \001(\014\022\025\n\rhashSignature\030\004" +
      " \001(\014\022\021\n\ttimestamp\030\005 \001(\014\022\036\n\021previousBlock" +
      "Hash\030\006 \001(\014H\000\210\001\001B\024\n\022_previousBlockHash\"E\n" +
      "\rBlockchainDto\0224\n\005chain\030\001 \003(\0132%.ru.itisl" +
      "abs.blockchains.dto.BlockDtoB/\n\033ru.itisl" +
      "abs.blockchains.dtoB\016BlockchainDtosP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ru_itislabs_blockchains_dto_BlockDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_itislabs_blockchains_dto_BlockDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itislabs_blockchains_dto_BlockDto_descriptor,
        new java.lang.String[] { "Id", "Data", "DataSignature", "HashSignature", "Timestamp", "PreviousBlockHash", });
    internal_static_ru_itislabs_blockchains_dto_BlockchainDto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_itislabs_blockchains_dto_BlockchainDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itislabs_blockchains_dto_BlockchainDto_descriptor,
        new java.lang.String[] { "Chain", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
